# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  config,
  modulesPath,
  pkgs,
  ...
}: let
  luksDevice = "/dev/disk/by-label/NIXCRYPT";
  rootDevice = "/dev/disk/by-label/NIXROOT";
  bootDevice = "/dev/disk/by-label/NIXBOOT";
  swapDevice = "/dev/disk/by-label/NIXSWAP";
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "dm-crypt"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  #  fileSystems."/" = {
  #    device = "${rootDevice}";
  #    fsType = "btrfs";
  #    options = ["subvol=root" "noatime" "compress=zstd"];
  #  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "size=4G"
      "mode=755"
    ];
  };

  # boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/21df6df8-33c2-4925-975b-d6d772c0b234";
  boot.initrd.luks.devices."crypt".device = "${luksDevice}";

  fileSystems."/home" = {
    device = "${rootDevice}";
    fsType = "btrfs";
    options = ["subvol=home" "noatime" "compress=zstd" "defaults"];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "${rootDevice}";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime" "compress=zstd" "defaults"];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "${rootDevice}";
    fsType = "btrfs";
    options = ["subvol=log" "noatime" "compress=zstd"];
  };

  fileSystems."/.snapshots" = {
    device = "${rootDevice}";
    fsType = "btrfs";
    options = ["subvol=snapshots" "defaults"];
  };

  fileSystems."/persistent" = {
    device = "${rootDevice}";
    fsType = "btrfs";
    options = ["subvol=persistent"];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "${bootDevice}";
    fsType = "vfat";
    options = ["defaults" "fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "${swapDevice}";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
