# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  config,
  modulesPath,
  pkgs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Raspberry Pi 3B — BCM2837 (ARM Cortex-A53)
  boot.initrd.availableKernelModules = ["usbhid" "usb_storage" "mmc_block" "vc4"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["brcmfmac" "brcmutil"];
  boot.extraModulePackages = [];
  boot.kernelParams = ["cma=256M"];

  # Filesystems are managed by the sd-image-aarch64 module for image builds.
  # Run nixos-generate-config on the Pi to get the correct values for deployment.

  # Firmware for WiFi/BT
  hardware.enableRedistributableFirmware = true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
