# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "dm-crypt" "aesni_intel"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@" "noatime" "compress=zstd" "defaults"];
    neededForBoot = true;
  };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/c237d262-2ecc-41a8-ae6d-72f8207b446e";

  fileSystems."/home" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd" "defaults"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=@nix" "noatime" "compress=zstd" "defaults"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
      options = [ "defaults" ];
      neededForBoot = true;
    };

  fileSystems."/nix" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd" "defaults"];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@log" "noatime" "compress=zstd" "defaults"];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@persist" "noatime" "compress=zstd" "defaults"];
    neededForBoot = true;
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=@snapshots" "noatime" "compress=zstd" "defaults"];

  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = ["mode=0755" "defaults"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/f4d33018-3dcd-4c46-ad81-1c4aacdc7bbd";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.enableAllFirmware = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
